// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_YeOrtjI0Hn4RTyk_O6ugTZvqgogEA8',
    appId: '1:134862941005:web:5893b5dc73d9e025ea2504',
    messagingSenderId: '134862941005',
    projectId: 'tuyano-sample-app-15408',
    authDomain: 'tuyano-sample-app-15408.firebaseapp.com',
    storageBucket: 'tuyano-sample-app-15408.firebasestorage.app',
    measurementId: 'G-MFGW8KJZHD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3_YeOrtjI0Hn4RTyk_O6ugTZvqgogEA8',
    appId: '1:134862941005:web:5870f0bd8b586fc4ea2504',
    messagingSenderId: '134862941005',
    projectId: 'tuyano-sample-app-15408',
    authDomain: 'tuyano-sample-app-15408.firebaseapp.com',
    storageBucket: 'tuyano-sample-app-15408.firebasestorage.app',
    measurementId: 'G-29VGFMH5PY',
  );
}
